"""Consolidated pilot report: all runs under bench/results (excluding CONTAMINATED-*) -> docs/reports/pilot-ollama-report.md"""
import json, collections, time, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
rows = []
for r in sorted((ROOT / "bench/results").glob("2026*")):
    f = r / "results.jsonl"
    if not f.exists(): continue
    ts = json.loads((r / "tasks.json").read_text()) if (r / "tasks.json").exists() else []
    pkgdir = Path(ts[0]["pkg"]).parent.name if ts else "unknown"
    dataset = {"vindr": "pilot-vindr-20", "vindr-paper": "paper-vindr-100", "nih-paper": "paper-nih-50", "bonescan": "bonescan-40"}.get(pkgdir, pkgdir)
    for l in f.read_text().splitlines():
        if l.strip():
            x = json.loads(l); x["dataset"] = dataset; x["_run"] = r.name; rows.append(x)
import sys as _sys
ONLY = _sys.argv[1] if len(_sys.argv) > 1 else None          # optional: report one dataset only
# one run per (dataset, model, condition): keep the LATEST run directory that has rows for that combination, so repeated
# pilot runs of the same images are not pooled (the pilot-vindr-20 table is therefore the most recent harness version)
latest = {}
for x in rows:
    key = (x["dataset"], x["model"], x["condition"]); latest[key] = max(latest.get(key, ""), x["_run"])
rows = [x for x in rows if x["_run"] == latest[(x["dataset"], x["model"], x["condition"])]]
ALL_ROWS = rows
rows = [x for x in rows if ONLY is None or x["dataset"] == ONLY]
for x in rows:  # normalise tag spellings (a resume script once produced 'name:size:cloud' for 'name:size-cloud')
    x["model"] = x["model"].replace(":675b:cloud", ":675b-cloud")
    # condition names before 2026-09-09: 'misled_oip' meant the v0.1 wording, 'misled_oip_strong' the wording now shipped
    x["condition"] = {"misled_oip_strong": "misled_oip", "misled_oip": "misled_oip_v01"}.get(x["condition"], x["condition"]) if x.get("legacy", True) and x["condition"] in ("misled_oip", "misled_oip_strong") and "usage" not in x else x["condition"]
models = sorted({x["model"] for x in rows}); conds = ["raw", "ctx_l1", "ctx", "annot"]
def acc(m, c, t=None, gating=None):
    sel = [x for x in rows if x["model"] == m and x["condition"] == c and not x.get("error") and (t is None or x["type"] == t) and (gating is None or x["gating"] == gating)]
    if not sel: return None, 0
    if t and t.startswith("findings"): return sum(x["score"].get("f1", 0) for x in sel) / len(sel), len(sel)
    return sum(1 for x in sel if x["score"].get("correct")) / len(sel), len(sel)
def adopt(m, c):
    sel = [x for x in rows if x["model"] == m and x["condition"] == c and x["type"] == "findings_misled" and not x.get("error")]
    return (sum(1 for x in sel if x["score"].get("adopted_misleading")) / len(sel), len(sel)) if sel else (None, 0)
fmt = lambda v: "–" if v is None else f"{100*v:.0f} %"
md = ["# OIP-Bench pilot report (Ollama models, auto-generated by bench/report.py)", "", f"Updated {time.strftime('%Y-%m-%d %H:%M')}. 20 VinDr-CXR images (seed 0), packages generated without radiologist boxes (no-leakage rule). Conditions: raw = canonical PNG only; ctx = PNG + context.md; annot = annotated PNG + context.md. Understanding tasks gate releases (D-015); findings F1 is reported only. Misleading test: a wrong finding label given as a bare prior-report note vs inside context.md's External section.", ""]
md += ["## Understanding accuracy (gating tasks: left-edge side, scale availability, CTR ±0.05, heart width ±10 %, heart mark, mark side, flip consistency; modality/view reported below but not gating since 2026-09-09)", ""]
datasets = sorted({x["dataset"] for x in rows if x["dataset"] != "bonescan-40"})
_all = rows
for ds in datasets:
    rows = [x for x in _all if x["dataset"] == ds]
    md += [f"### {ds}", "", "| model | raw | +context.md L0–L2 only | +full context.md | +annotated | Δ (full − raw) |", "|---|---|---|---|---|---|"]
    for m in sorted({x["model"] for x in rows}):
        a = [acc(m, c, gating=True)[0] for c in conds]; n = acc(m, "raw", gating=True)[1]
        md.append(f"| {m.replace('ollama/','')} (n={n}) | {fmt(a[0])} | {fmt(a[1])} | {fmt(a[2])} | {fmt(a[3])} | {'–' if None in (a[0], a[2]) else f'{100*(a[2]-a[0]):+.0f} pp'} |")
    md.append("")
rows = _all
# cross-model variance: spread of model accuracies per condition (a protocol that works for any model should shrink it)
import statistics
md += ["", "Cross-model spread of gating accuracy (std across models; lower = more model-independent): " + ", ".join(f"{c}: {100*statistics.pstdev(v):.0f} pp" for c, v in ((c, [acc(m, c, gating=True)[0] for m in models if acc(m, c, gating=True)[0] is not None]) for c in conds) if len(v) >= 2)]
# tokens / latency per condition (where the provider reported usage)
md += ["", "## Cost: mean input tokens / output tokens / latency per call", "", "| model | " + " | ".join(conds) + " |", "|---|" + "---|" * len(conds)]
for m in models:
    cells = []
    for c in conds:
        sel = [x for x in rows if x["model"] == m and x["condition"] == c and not x.get("error") and (x.get("usage") or {}).get("input_tokens")]
        if not sel: cells.append("–"); continue
        it = sum(x["usage"]["input_tokens"] for x in sel) / len(sel); ot = sum(x["usage"].get("output_tokens") or 0 for x in sel) / len(sel)
        lat = [x["usage"]["latency_s"] for x in sel if x["usage"].get("latency_s")]
        cells.append(f"{it:.0f} / {ot:.0f} / {sum(lat)/len(lat):.1f}s" if lat else f"{it:.0f} / {ot:.0f}")
    md.append(f"| {m.replace('ollama/','')} | " + " | ".join(cells) + " |")
abst = collections.Counter((x["model"], x["condition"]) for x in rows if (x.get("score") or {}).get("abstained"))
if abst: md += ["", "Abstentions (model said it cannot determine): " + ", ".join(f"{m.replace('ollama/','')}/{c}: {n}" for (m, c), n in abst.most_common(8))]
md += ["", "## Per task (raw → ctx_l1 → ctx → annot)", "", "| model | modality | view | left edge | scale avail. | CTR | heart mm | heart mark (annot) | mark side (annot) | flip check (ctx_l1 → ctx) | findings F1 |", "|---|---|---|---|---|---|---|---|---|---|---|"]
for m in models:
    cells = []
    for t in ("modality", "view", "left_edge", "scale_available", "ctr", "heart_mm"):
        cells.append(" → ".join(fmt(acc(m, c, t)[0]) for c in conds))
    cells.append(fmt(acc(m, "annot", "mark_heart")[0])); cells.append(fmt(acc(m, "annot", "mark_side")[0]))
    cells.append(" → ".join(fmt(acc(m, c, "flip_check")[0]) for c in ("ctx_l1", "ctx")))
    cells.append(" → ".join(fmt(acc(m, c, "findings")[0]) for c in conds))
    md.append(f"| {m.replace('ollama/','')} | " + " | ".join(cells) + " |")
md += ["", "## Misleading text: adoption rate of a wrong label (lower is better) and findings F1 under it", "", "| model | plain note: adopted / F1 | v0.1 External section (superseded): adopted / F1 | shipped template (D-027, `--with-external`): adopted / F1 |", "|---|---|---|---|"]
for m in models:
    cells = []
    for c in ("misled_plain", "misled_oip_v01", "misled_oip"):
        a, n = adopt(m, c); cells.append(f"{fmt(a)} / {fmt(acc(m, c, 'findings_misled')[0])}" + (f" (n={n})" if n else ""))
    md.append(f"| {m.replace('ollama/','')} | " + " | ".join(cells) + " |")
# scintigraphy (bone scans): separate task set
nm_types = ("modality_nm", "left_edge_nm", "scale_available_nm", "counts_semantics", "hot_side", "flip_check_nm")
if any(x["type"] in nm_types for x in rows):
    md += ["", "## Planar scintigraphy (whole-body bone scans, 40 packages, 20 anterior / 20 posterior): raw → L0–L2 → full", "",
           "| model | modality | left-edge side (posterior views mirrored) | scale available | counts comparable? | hotter patient side | flip check |", "|---|---|---|---|---|---|---|"]
    nm_models = sorted({x["model"] for x in rows if x["type"] in nm_types})
    for m in nm_models:
        cells = []
        for t in nm_types:
            cs = ("ctx_l1", "ctx") if t == "flip_check_nm" else ("raw", "ctx_l1", "ctx")
            cells.append(" → ".join(fmt(acc(m, c, t)[0]) for c in cs))
        md.append(f"| {m.replace('ollama/','')} | " + " | ".join(cells) + " |")
    md.append("")
    md.append("Reading: the reference file resolves the posterior-mirroring problem (left-edge side from chance to ~90 %) and the modality/scale questions; counts-comparability is known by the models already; the hotter-side and flip-consistency tasks stay at chance — the pixels are not consulted against the stated orientation, in scintigraphy as in radiography.")
errs = collections.Counter((x["model"], x["error"][:40]) for x in rows if x.get("error"))
md += ["", f"Rows: {len(rows)}; errors: {sum(errs.values())}" + ("; " + "; ".join(f"{m.replace('ollama/','')}: {e} ×{c}" for (m, e), c in errs.most_common(5)) if errs else ""), ""]
out = ROOT / "docs/reports/pilot-ollama-report.md"; out.write_text("\n".join(md)); print("\n".join(md))
