"""Count-recovery report for the bone-scan packages: how many stretched 8/16-bit PNGs yielded a recovered count scale.

The Paraguay bone scans ship as contrast-stretched PNGs; scripts/bonescan_to_oip.py tries to recover the quantisation lattice of the
original counts (extension `org.openimageprotocol.counts_recovery`: quantisation step and estimated maximum counts, assertion level
inferred). This report counts successes over a package set and summarises the recovered values, so the number no longer lives only in
PLAN.md. Usage: python scripts/bonescan_recovery_report.py [pkg_dir ...]  (default: $OIP_BENCH_DIR/bonescan) -> docs/reports/bonescan-count-recovery.md
"""
from __future__ import annotations
import json, os, statistics, sys, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXT = "org.openimageprotocol.counts_recovery"
dirs = [Path(p) for p in sys.argv[1:]] or [Path(os.environ.get("OIP_BENCH_DIR", Path.home() / "oip-bench")) / "bonescan"]
L = [f"# Bone-scan count recovery (auto-generated by scripts/bonescan_recovery_report.py, {time.strftime('%Y-%m-%d %H:%M')})", "",
     "Source PNGs are contrast-stretched; a package counts as *recovered* when the adapter found the quantisation lattice and stored "
     "`org.openimageprotocol.counts_recovery` (quantisation step, estimated maximum counts; assertion level inferred). Without it the "
     "pixels stay stretched values with the `counts_not_comparable` flag. Recovery affects only the stated count scale; renders, "
     "orientation and the benchmark tasks do not depend on it.", ""]
for d in dirs:
    pkgs = sorted(p for p in d.glob("*.oip") if (p / "oip.json").exists())
    rec = []; views = {"recovered": {}, "not": {}}
    for p in pkgs:
        m = json.loads((p / "oip.json").read_text()); e = (m.get("extensions") or {}).get(EXT)
        view = str((m["acquisition"].get("view") or {}).get("value") or "?")
        if e and e.get("quantisation_step"):
            rec.append(e); views["recovered"][view] = views["recovered"].get(view, 0) + 1
        else:
            views["not"][view] = views["not"].get(view, 0) + 1
    n = len(pkgs); k = len(rec)
    L += [f"## {d}", "", f"- packages: {n}; recovered: {k} ({100*k/n:.0f} %); not recovered: {n-k}" if n else f"- no packages under {d}"]
    if rec:
        steps = [e["quantisation_step"] for e in rec]; mx = [e["estimated_max_counts"] for e in rec if e.get("estimated_max_counts")]
        L += [f"- quantisation step: median {statistics.median(steps):.1f} (min {min(steps):.1f}, max {max(steps):.1f})",
              f"- estimated maximum counts per image: median {statistics.median(mx):.0f} (min {min(mx)}, max {max(mx)})" if mx else "- estimated maximum counts: not stored"]
    L += [f"- by view, recovered: {views['recovered']}; not recovered: {views['not']}", ""]
out = ROOT / "docs/reports/bonescan-count-recovery.md"; out.write_text("\n".join(L) + "\n"); print("\n".join(L))
