"""Summarise data/oip/<dataset>/_measure.json + _per_image.json into docs/reports/phase2-measurement-report.md."""
import json, statistics, sys, time
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
names = sys.argv[1:] or ["vindr"]
md = ["# Phase 2 measurement report (auto-generated by scripts/measure_report.py)", "", f"Updated {time.strftime('%Y-%m-%d %H:%M')}. Model: TorchXRayVision PSPNet (ChestX-Det). All values `inferred`/`computed`, validation status `unvalidated` until Tier-2 (CheXmask) agreement is measured.", ""]
for name in names:
    d = ROOT / "data/oip" / name
    if not (d / "_measure.json").exists():
        md.append(f"### {name}\n- no measurement run yet\n"); continue
    mres = json.load(open(d / "_measure.json")); per = {x["file"].split(".")[0]: x for x in json.load(open(d / "_per_image.json"))} if (d / "_per_image.json").exists() else {}
    rows = []
    for r in mres["results"]:
        if "error" in r or not r.get("ctr"): continue
        pkg = d / r["pkg"]; m = json.loads((pkg / "oip.json").read_text())
        meas = {x["id"]: x for x in m["derived"]["measurements"]}
        rows.append(dict(ctr=r["ctr"], heart_mm=meas.get("heart_width", {}).get("value"), thorax_mm=meas.get("thorax_width", {}).get("value"),
                         spacing=m["geometry"]["spacing_source"], conf=m["geometry"]["calibration"]["confidence"], regions=len(m["derived"]["regions"]), lat="check orientation" in " ".join(m["quality"].get("notes", []))))
    ctrs = sorted(x["ctr"] for x in rows); q = lambda p: ctrs[int(p * (len(ctrs) - 1))] if ctrs else None
    md += [f"### {name}", f"- images measured: {mres['n']} · with CTR: {len(rows)} · errors: {mres['errors']} · {mres['seconds_per_image']} s/image (CPU)",
           f"- regions per image: {statistics.mean(x['regions'] for x in rows):.1f} (heart, lungs, spine, aorta, mediastinum, clavicles, diaphragm when detected)",
           f"- CTR: median {q(0.5):.3f}, p10 {q(0.1):.3f}, p90 {q(0.9):.3f}, min {ctrs[0]:.3f}, max {ctrs[-1]:.3f}; CTR > 0.50 in {sum(c > 0.5 for c in ctrs)} ({100*sum(c > 0.5 for c in ctrs)/len(ctrs):.0f} %) — VinDr has ~18 % cardiomegaly labels, so this order of magnitude is expected",
           f"- laterality sanity check flagged: {sum(x['lat'] for x in rows)} images (left/right structure found on the wrong image side)"]
    mm = [x for x in rows if x["heart_mm"]]
    if mm:
        hw = sorted(x["heart_mm"] for x in mm); tw = sorted(x["thorax_mm"] for x in mm)
        md.append(f"- mm widths reported for {len(mm)} images (calibrated spacing present), refused for {len(rows)-len(mm)}: heart width median {hw[len(hw)//2]:.0f} mm (p10 {hw[len(hw)//10]:.0f}, p90 {hw[9*len(hw)//10]:.0f}); thoracic width median {tw[len(tw)//2]:.0f} mm (p10 {tw[len(tw)//10]:.0f}, p90 {tw[9*len(tw)//10]:.0f}). Adult reference: heart ~110–140 mm, thorax ~280–350 mm.")
        by = {}
        for x in mm: by.setdefault(x["conf"], []).append(x["thorax_mm"])
        md.append("- thoracic width by spacing confidence: " + "; ".join(f"{k}: n={len(v)}, median {sorted(v)[len(v)//2]:.0f} mm" for k, v in by.items()))
    md.append("")
(ROOT / "docs/reports/phase2-measurement-report.md").write_text("\n".join(md)); print("\n".join(md))
